# Generated by Django 2.2 on 2021-01-30 07:40

import ckeditor.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('display_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('presentation_image', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name': 'Advertisement',
                'verbose_name_plural': 'Advertisements',
            },
        ),
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('display_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'News Category',
                'verbose_name_plural': 'News Categories',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=200, unique=True)),
                ('description', models.CharField(max_length=200)),
                ('is_default', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('National', 'National'), ('International', 'International')], default='National', max_length=20)),
                ('author', models.CharField(blank=True, max_length=50, null=True)),
                ('title', models.CharField(max_length=200, unique=True)),
                ('synopsis', models.CharField(blank=True, max_length=100, null=True)),
                ('summary', ckeditor.fields.RichTextField()),
                ('date', models.DateField(default=datetime.date.today)),
                ('body', ckeditor.fields.RichTextField()),
                ('presentation_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('views_counter', models.PositiveIntegerField(default=0)),
                ('likes_counter', models.PositiveIntegerField(default=0)),
                ('create_ts', models.DateTimeField(default=datetime.datetime.now)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cat_news', to='news.NewsCategory')),
                ('tags', models.ManyToManyField(blank=True, to='news.Tags')),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
            },
        ),
    ]
