# Generated by Django 2.2.17 on 2021-01-30 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newscategory',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
