# Generated by Django 2.2 on 2019-08-18 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='synopsis',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
