# Generated by Django 2.2 on 2019-08-18 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_synopsis'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='type',
            field=models.CharField(choices=[('National', 'National'), ('International', 'International')], default='National', max_length=20),
        ),
    ]
