# Generated by Django 2.2 on 2019-08-24 19:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20190818_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='create_ts',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
