# Generated by Django 2.2 on 2019-08-24 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20190825_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='synopsis',
            field=models.TextField(blank=True, null=True),
        ),
    ]
