# Generated by Django 2.2 on 2019-08-24 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20190825_0059'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='synopsis',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
