# Generated by Django 2.2 on 2019-08-25 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_auto_20190825_0059'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='likes_counter',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='news',
            name='presentation_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='news',
            name='views_counter',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
