# Generated by Django 2.2 on 2019-08-26 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_auto_20190825_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='tags',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
