# Generated by Django 2.2 on 2019-08-26 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_tags_is_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='synopsis',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
