# Generated by Django 2.2 on 2019-08-27 03:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_news_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='newscategory',
            name='display_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tags',
            name='display_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
