# Generated by Django 2.2 on 2019-08-27 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0015_auto_20190827_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='display_name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
