# Generated by Django 2.2 on 2019-09-08 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0017_auto_20190908_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
