# Generated by Django 2.2 on 2019-09-08 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0018_auto_20190908_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='display_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ads',
            name='url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
