# Generated by Django 2.2 on 2020-06-30 12:08

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0020_auto_20200630_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='summary',
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
    ]
