# Generated by Django 2.2 on 2020-04-26 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube', models.CharField(max_length=200, null=True, verbose_name='YouTube')),
                ('twitter', models.CharField(max_length=200, null=True, verbose_name='Twitter')),
                ('instagram', models.CharField(max_length=200, null=True, verbose_name='Instagram')),
                ('facebook', models.CharField(max_length=200, null=True, verbose_name='Facebook')),
                ('linkedin', models.CharField(max_length=200, null=True, verbose_name='LinkedIn')),
                ('reddit', models.CharField(max_length=200, null=True, verbose_name='Reddit')),
                ('discord', models.CharField(max_length=200, null=True, verbose_name='Discord')),
            ],
        ),
    ]
