# Generated by Django 2.2 on 2021-01-30 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube', models.CharField(blank=True, max_length=200, null=True, verbose_name='YouTube')),
                ('twitter', models.CharField(blank=True, max_length=200, null=True, verbose_name='Twitter')),
                ('instagram', models.CharField(blank=True, max_length=200, null=True, verbose_name='Instagram')),
                ('facebook', models.CharField(blank=True, max_length=200, null=True, verbose_name='Facebook')),
                ('linkedin', models.CharField(blank=True, max_length=200, null=True, verbose_name='LinkedIn')),
                ('reddit', models.CharField(blank=True, max_length=200, null=True, verbose_name='Reddit')),
            ],
        ),
    ]
