# Generated by Django 2.2 on 2020-04-26 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='social',
            name='discord',
        ),
    ]
