# Generated by Django 2.2 on 2020-04-26 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_remove_social_discord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='facebook',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='social',
            name='instagram',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='social',
            name='linkedin',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='LinkedIn'),
        ),
        migrations.AlterField(
            model_name='social',
            name='reddit',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Reddit'),
        ),
        migrations.AlterField(
            model_name='social',
            name='twitter',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Twitter'),
        ),
        migrations.AlterField(
            model_name='social',
            name='youtube',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='YouTube'),
        ),
    ]
